In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')


import sys
sys.path.insert (0, './_functions_/')
from functions_eda import *

In [5]:
df = pd.read_csv('./rhein-kreis-neuss-fahrzeugbestand.csv',sep=';')
df.head(30)

,Kennzeichen,Erstzulassung,Postleitzahl,Standort,Geburtsjahr Halter,Fahrzeugklasse,Hersteller,Aufbauart,Kraftstoffart,Emissionsklasse,CO₂-Emissionen,Hubraum,Leistung (kW),Farbe,Sitzplätze
0,NE,1985,41516,Grevenbroich,1960-1969,Krad,HARLEY-DAVIDSON,0,Benzin,0,0,1338,47,0,2
1,NE,2004,41462,Neuss,1960-1969,Krad,BAYER.MOT.WERKE-BMW,0,Benzin,EURO 2,0,1170,45,0,2
2,NE,1984,41460,Neuss,0,Pkw,VOLKSWAGEN-VW,0,Benzin,0,0,1035,29,Gelb,5
3,NE,1977,41470,Neuss,1960-1969,Pkw,BAYER.MOT.WERKE-BMW,0,Benzin,0,0,2478,110,Gelb,5
4,NE,1993,41541,Dormagen,1960-1969,Krad,HONDA MOTOR,0,Benzin,0,0,583,37,0,2
5,NE,1983,41564,Kaarst,1940-1949,Pkw,OPEL,0,Benzin,0,0,1587,66,Rot,5
6,NE,1974,41515,Grevenbroich,1960-1969,Pkw,VOLKSWAGEN-VW,0,Benzin,0,0,1281,40,0,5
7,NE,1981,41460,Neuss,1970-1979,Anhänger,HEINEMANN,0,0,0,0,0,0,0,0
8,NE,2004,41541,Dormagen,1940-1949,Pkw,GM DAEWOO,0,Benzin,EURO 3,0,1598,80,Blau,5
9,NE,1978,41464,Neuss,1960-1969,Anhänger,TECHAU,0,0,0,0,0,0,0,0
10,NE,1999,41564,Kaarst,1950-1959,Krad,BAYER.MOT.WERKE-BMW,0,Benzin,0,0,1085,66,0,2
11,NE,1983,41516,Grevenbroich,0,Anhänger,KRUELL,0,0,0,0,0,0,0,0
12,NE,2005,40670,Meerbusch,1930-1939,Pkw,VOLKSWAGEN-VW,0,Benzin,EURO 4,0,1984,85,Grau,5
13,NE,1999,41515,Grevenbroich,1950-1959,Krad,MONTESA HONDA S.A.,0,Benzin,0,0,125,8,0,2
14,NE,1996,40670,Meerbusch,1960-1969,Krad,BAYER.MOT.WERKE-BMW,0,Benzin,0,0,797,37,0,2
15,NE,2002,41466,Neuss,1950-1959,Sonder-Kfz,FIAT,0,Diesel,EURO 3,0,2800,94,0,6
16,NE,1986,40667,Meerbusch,1950-1959,Anhänger,CARBO B.V.,0,0,0,0,0,0,0,0
17,NE,1994,40667,Meerbusch,1950-1959,Pkw,CITROEN,0,Benzin,EURO 1,0,1998,108,Grün,7
18,NE,2002,41516,Grevenbroich,1970-1979,Pkw,VOLKSWAGEN-VW,0,Benzin,EURO 4,0,1390,55,Grau,5
19,NE,1977,41462,Neuss,1920-1929,Pkw,FORD,0,Benzin,0,0,1981,66,0,5
20,NE,1981,41569,Rommerskirchen,1940-1949,Zugmaschine,RENAULT,0,Diesel,0,0,3744,48,0,2
21,NE,1969,41468,Neuss,1920-1929,Pkw,S.A.PEUGEOT,0,Benzin,0,0,1607,76,Weiss,5
22,NE,1954,41569,Rommerskirchen,1930-1939,Krad,ADLERWERKE,0,Benzin,0,0,195,8,0,2
23,NE,1996,40668,Meerbusch,1940-1949,Pkw,CHRYSLER,0,Benzin,EURO 2,0,2429,110,Blau,7
24,NE,1973,41468,Neuss,1960-1969,Anhänger,"BÖCKMANN, ANTON",0,0,0,0,0,0,0,0
25,NE,1980,41468,Neuss,1920-1929,Pkw,BAYER.MOT.WERKE-BMW,0,Benzin,0,0,1977,90,Grün,5
26,NE,1988,41516,Grevenbroich,1940-1949,Pkw,BAYER.MOT.WERKE-BMW,0,Benzin,EURO 2,0,1976,95,Grau,5
27,NE,1981,41541,Dormagen,1960-1969,Pkw,FIAT,0,Benzin,0,0,1465,63,Weiss,5
28,NE,1988,41462,Neuss,0,Pkw,DAIMLER-BENZ,0,Benzin,EURO 1,0,2548,118,Grau,5
29,NE,1982,41460,Neuss,0,Pkw,FORD,0,Benzin,0,0,1954,77,Grau,5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fuel_type  42 non-null     object
 1   pkw        42 non-null     object
 2   total      42 non-null     object
 3   Jahr       42 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.4+ KB

In [18]:
relevant_columns = [ 'Erstzulassung', 'Postleitzahl', 'Standort',
       'Geburtsjahr Halter', 'Kraftstoffart', 'Leistung (kW)']
df = df [relevant_columns]

In [19]:
df = df[df["Erstzulassung"] > 2014]
df.head(10)

,Erstzulassung,Postleitzahl,Standort,Geburtsjahr Halter,Kraftstoffart,Leistung (kW)
3390,2018,41363,Jüchen,1960-1969,Benzin,110
3391,2018,41564,Kaarst,1980-1989,Benzin,60
3392,2018,41352,Korschenbroich,1960-1969,Benzin,96
3394,2018,41564,Kaarst,1940-1949,Benzin,81
3395,2018,41470,Neuss,0,Diesel,120
3396,2018,41462,Neuss,0,Diesel,110
3397,2018,41462,Neuss,0,Benzin,110
3398,2018,41541,Dormagen,1960-1969,Benzin,97
3401,2017,41466,Neuss,1970-1979,Diesel,140
3402,2018,41540,Dormagen,0,Diesel,96

In [20]:
df["Erstzulassung"].value_counts()

Erstzulassung
2019    22007
2018    20246
2017    19299
2016    18260
2020    17997
2022    17068
2021    16963
2023    16713
2015    16646
2024     6994
Name: count, dtype: int64

In [27]:
df['Kraftstoffart'].value_counts()

Kraftstoffart
Benzin      97956
Diesel      45229
Hybrid E    19454
Elektro      8532
Hybrid        823
Gas           199
Name: count, dtype: int64

In [21]:
# Keep only rows where count is the type of Kraftstoff is in one category that has more than 20 elements
value_counts = df['Kraftstoffart'].value_counts()
df = df[df['Kraftstoffart'].isin(value_counts[value_counts >= 20].index)]

In [23]:
# harmonize the types of "Kraftstoffart"

kraftstoffart_mapping = {
 'Benzin': 'Benzin', 
 'Diesel': 'Diesel', 
 'Hybr.Benzin/E': 'Hybrid E', 
 'Elektro': 'Elektro', 
 'Hybr.B/E ext.aufl.': 'Hybrid E', 
 'Hybr.Diesel/E': 'Hybrid E', 
 'Benzin/Flüssiggas': 'Hybrid', 
 'Hybr.D/E ext.aufl.': 'Hybrid E', 
 'Erdgas NG': 'Gas', 
 'Benzin/komp.Erdgas': 'Hybrid', 
 }

df['Kraftstoffart'] = df['Kraftstoffart'].replace(kraftstoffart_mapping)
df["Kraftstoffart"].value_counts()

Kraftstoffart
Benzin      97956
Diesel      45229
Hybrid E    19454
Elektro      8532
Hybrid        823
Gas           199
Name: count, dtype: int64

In [24]:
# replace this Kraftstoffart that has a value of 0, which in this case is a NAN with the mode.
mode_kraftstoffart = df['Kraftstoffart'].mode().iloc[0]  # Extract the most frequent value
df['Kraftstoffart'] = df['Kraftstoffart'].str.replace('0', mode_kraftstoffart)
df["Kraftstoffart"].value_counts()

Kraftstoffart
Benzin      97956
Diesel      45229
Hybrid E    19454
Elektro      8532
Hybrid        823
Gas           199
Name: count, dtype: int64

In [25]:
percentage_null_values(df)

                    Percentage_NaN
Erstzulassung                  0.0
Postleitzahl                   0.0
Standort                       0.0
Geburtsjahr Halter             0.0
Kraftstoffart                  0.0
Leistung (kW)                  0.0